---
title: "GSEA_mRNA"
author: "Francis Leblanc"
date: "23/11/2020"
output:   
  html_document:
    toc: yes
    toc_float: yes
    number_sections: true
    code_folding: hide 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(rio)
library(limma)
```

# GSEA for DE mRNAs 


```{r}
all_res <- import("data/final/all.raw_expression.RDS")
pval.cols <- c("CTLvsAVBpadj","CTLvsATPpadj","AVBvsATPpadj")

# set these variables to numeric
all_res[,pval.cols] <- lapply(all_res[,pval.cols],as.numeric)
mRNA <- all_res %>% dplyr::filter(Dataset == "mRNA")

# make up and downregulated geneset for each contrasts
l <- list()
cols <- grep("padj",colnames(mRNA))
cols <- cols[1:3]

for (i in 1:3) {
  x <- mRNA[order(mRNA[,cols[i]]),]
  l[[paste0("up.",substr(colnames(x)[cols[i]-1],6,8),"vs",substr(colnames(x)[cols[i]-1],1,3))]] <- x$Gene[which(x[,cols[i]] < 0.01 & x[,(cols[i]-1)] < 0)]
  
  l[[paste0("down.",substr(colnames(x)[cols[i]-1],6,8),"vs",substr(colnames(x)[cols[i]-1],1,3))]] <- x$Gene[which(x[,cols[i]] < 0.01 & x[,(cols[i]-1)] > 0)]
}

library(hypeR)
library(msigdbr)
msigdb_path <- msigdb_download_all(species="Homo sapiens")

GSEA <- hypeR("test", msigdb_path, fdr_cutoff = 0.01, test = "hypergeometric", do_plots=TRUE)
geneset <- msigdb_fetch(msigdb_path, "C5.BP")

all_path <- GSEA$as.data.frame()
all_path$DB <- character()
all_path$contrast <- character()

for (i in names(l)) {
    sign <- unique(l[[i]])
    sign <- sign[!(is.na(sign))]

    GSEA <- hypeR(sign, geneset, fdr_cutoff = 0.01, test = "hypergeometric", do_plots=T)
    GSEA_df <- GSEA$as.data.frame()
    if (nrow(GSEA_df) > 0) {
            GSEA_df <- GSEA_df[order(GSEA_df$fdr),]
            GSEA_df$label <- factor(GSEA_df$label, levels = GSEA_df$label[order(GSEA_df$fdr, decreasing = T)])
            GSEA_df$DB <- "C5.BP"
            GSEA_df$contrast <- i
            all_path <- rbind(all_path,GSEA_df)
    }
}

rio::export(all_path,"data/final/all_mRNA_pathways.xlsx")
```

## Make table of genes in pathways ordered by fdr

```{r}
all_path <- import("data/final/all_mRNA_pathways.xlsx")
GO_BP <- all_path %>% dplyr::select(-DB)

GO_BP$contrast <- factor(GO_BP$contrast, levels=unique(GO_BP$contrast))

for (i in levels(GO_BP$contrast)) {
  for (j in 1:5) {
    labels <- GO_BP %>% dplyr::filter(contrast == i) %>% pull(label)
    hit <- GO_BP %>% dplyr::filter(contrast == i) %>% dplyr::select(hits)
    hit <- strsplit(hit[j,],",")[[1]]
    GO_BP$hits_ordered[GO_BP$contrast == i & GO_BP$label == labels[j]] <- paste(hit, collapse = ", ")
  }
}

# keep top 5 for each set
GO_BP <- GO_BP %>% filter(!is.na(hits_ordered))
top5 <- GO_BP
top5[,9:18] <- NA
colnames(top5)[9:18] <- paste0("Rank_",seq(10),"_gene")

# order genes by fdr
for (i in 1:nrow(GO_BP)) {
 hits <- strsplit2(GO_BP[i, "hits_ordered"] ,", ")
 top5[i,9:18] <- hits[,1:10]
}
GO_BP <- cbind(GO_BP, top5[,9:18])

rio::export(GO_BP, "data/final/mRNA_DogAF.GO_BP.xlsx")
```

# GSEA for dlk1-dio3 locus targets

```{r}
targets <- import("../miRNA/data/final/dlk1_dio3_targets.RDS")

targets_names <- targets %>% 
  pull(SYMBOL) %>% 
  unique()

GSEA <- hypeR(targets_names, geneset, fdr_cutoff = 0.1, test = "hypergeometric", do_plots=F)
all_path <- GSEA$as.data.frame()
export(all_path,"data/final/dlk1_dio3_GO_BP.RDS")
```

